spring.application.name=cinema

# H2 datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=dx4NbNZnONa3uoJOxGi8vUvPsBXfbXf0guaQubGjz78=
jwt.expiration=3600000

app.default-admin.username=admin
app.default-admin.password=adminpassword123@
app.default-admin.email=admin@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ksebi500@gmail.com
spring.mail.password=mnddosyqvslluwpx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
